repos:
- repo: https://github.com/pre-commit/pre-commit-hooks 
  rev: v2.3.0
  hooks:
  - id: check-merge-conflict
- repo: https://github.com/pre-commit/mirrors-mypy 
  rev: v1.2.0
  hooks:
  - id: mypy
    args: [src]
- repo: https://github.com/charliermarsh/ruff-pre-commit 
  rev: v0.0.261
  hooks:
  - id: ruff
- repo: https://github.com/codespell-project/codespell 
  rev: v2.2.4
  hooks:
  - id: codespell